import { test, expect, type Page } from '@playwright/test';
import { login, requireTeacherCredentials, requireStudentCredentials } from '../helpers/auth';

const teacherCreds=requireTeacherCredentials(), studentCreds=requireStudentCredentials();
type Wire={dir:'sent'|'recv';topic:string|null;event:string|null;status:string|null;reason:string|null;kind:string|null;value:string|null};
function parse(raw:string):Omit<Wire,'dir'>|null{try{const x=JSON.parse(raw);const o=Array.isArray(x)?{topic:x[2],event:x[3],payload:x[4]}:x;const topic=o?.topic!=null?String(o.topic):null;if(!topic?.startsWith('realtime:exsync-'))return null;const p=o?.payload??null,inner=p?.payload??null;return{topic,event:o?.event!=null?String(o.event):null,status:p?.status!=null?String(p.status):null,reason:p?.response?.reason!=null?String(p.response.reason):(p?.response?.error!=null?String(p.response.error):null),kind:inner?.kind!=null?String(inner.kind):null,value:inner?.value!=null?String(inner.value):null}}catch{return null}}
function capture(page:Page,sink:Wire[]){page.on('websocket',ws=>{if(!ws.url().includes('/realtime/'))return;ws.on('framesent',f=>{const w=parse(typeof f.payload==='string'?f.payload:String(f.payload));if(w)sink.push({...w,dir:'sent'})});ws.on('framereceived',f=>{const w=parse(typeof f.payload==='string'?f.payload:String(f.payload));if(w)sink.push({...w,dir:'recv'})})})}
async function app<T>(p:Page,e:string):Promise<T>{return p.evaluate(x=>(0,eval)(x),e) as Promise<T>}
async function setAuth(p:Page){await app(p,`(async()=>{const {data,error}=await sb.auth.getSession();if(error)throw error;if(!data?.session?.access_token)throw new Error('no token');await sb.realtime.setAuth(data.session.access_token);return true})()`) }
async function enterTeacher(p:Page){const c=p.locator('.ev-class-card:not(.ev-class-create)').first();await expect(c).toBeVisible();await c.click();await expect(p.locator('#classroomView')).toHaveClass(/open/)}
async function enterStudent(p:Page){await p.locator('#nav_s_classes').click();const b=p.getByRole('button',{name:/В урок/}).first();await expect(b).toBeVisible();await b.click();await expect(p.locator('#classroomView')).toHaveClass(/open/)}

test('wire: prove exsync auth inputs and delivery',async({browser})=>{test.setTimeout(90_000);const tc=await browser.newContext(),sc=await browser.newContext();const t=await tc.newPage(),s=await sc.newPage();const tw:Wire[]=[],sw:Wire[]=[];capture(t,tw);capture(s,sw);let classId:string|null=null,lessonId:string|null=null;try{
await login(t,teacherCreds);await login(s,studentCreds);await setAuth(t);await setAuth(s);
const fx=await app<{classId:string;lessonId:string}>(t,`(async()=>{const studentProfileId='${await app<string>(s,'S.profile.id')}';const {data:sp}=await sb.from('profiles').select('email').eq('id',studentProfileId).single();const {data:sr}=await sb.from('students').select('id,email').ilike('email',sp.email).eq('school_id',S.schoolId).limit(1);if(!sr?.length)throw new Error('student roster missing');const studentId=sr[0].id;const {data:cs,error:cse}=await sb.from('class_students').select('class_id').eq('student_id',studentId).eq('school_id',S.schoolId);if(cse)throw cse;const classIds=(cs||[]).map(x=>x.class_id);const {data:c,error:ce}=await sb.from('classes').select('id').eq('school_id',S.schoolId).eq('teacher_id',S.profile.id).in('id',classIds).limit(1);if(ce)throw ce;if(!c?.length)throw new Error('no shared teacher/student class');const classId=c[0].id;const {data:l,error:le}=await sb.from('lessons').insert({school_id:S.schoolId,teacher_id:S.profile.id,title:'E2E EXSYNC WIRE '+Date.now(),language:'English',level:'B1',published:true,exercise_count:0,content:{sections:[{title:'One',exercises:[]},{title:'Two',exercises:[]}],materials:[]}}).select('id').single();if(le)throw le;const {error:pe}=await sb.from('class_lessons').insert({school_id:S.schoolId,class_id:classId,lesson_id:l.id,position:999});if(pe)throw pe;return {classId,lessonId:l.id}})()`);classId=fx.classId;lessonId=fx.lessonId;
await enterTeacher(t);await enterStudent(s);await s.waitForTimeout(2500);
const teacherRoom=await app<string>(t,'LV._syncRoomKey');
const diag=await app<any>(s,`(async()=>{const {data:auth,error:ae}=await sb.rpc('exsync_authorized',{p_roomkey:'${teacherRoom}'});const {data:me}=await sb.from('profiles').select('email').eq('id',S.profile.id).single();const {data:rows}=await sb.from('students').select('id,email').ilike('email',me.email).eq('school_id',S.schoolId);const exact=(rows||[]).some(r=>r.email===me.email),lower=(rows||[]).some(r=>String(r.email).toLowerCase()===String(me.email).toLowerCase());const ids=(rows||[]).map(r=>r.id);let member=false;if(ids.length){const {data:cs}=await sb.from('class_students').select('class_id').eq('class_id','${classId}').in('student_id',ids);member=!!cs?.length}return {auth,authError:ae?String(ae.message||ae):null,exactEmailMatch:exact,lowerEmailMatch:lower,member,room:LV._syncRoomKey,state:LV._syncCh?.state,ready:LV._syncReady,currentClassId:S.currentClassId}})()`);
const tstate=await app<any>(t,'({room:LV._syncRoomKey,state:LV._syncCh?.state,ready:LV._syncReady,currentClassId:S.currentClassId})');console.log('[wire auth diagnostic]',JSON.stringify({teacher:tstate,student:diag}));console.log('[wire teacher pre]',JSON.stringify(tw.slice(-20)));console.log('[wire student pre]',JSON.stringify(sw.slice(-20)));
expect(diag.member).toBe(true);expect(diag.lowerEmailMatch).toBe(true);expect(diag.auth).toBe(true);expect(tstate.room).toBe(diag.room);
await expect.poll(()=>app<boolean>(t,'LV._syncReady===true'),{timeout:10000}).toBe(true);await expect.poll(()=>app<boolean>(s,'LV._syncReady===true'),{timeout:10000}).toBe(true);
const result=await app<any>(t,`(async()=>await LV._syncCh.send({type:'broadcast',event:'ex',payload:{id:'wire-${Date.now()}',kind:'section',value:'1',from:S.profile.id}}))()`);console.log('[wire send]',JSON.stringify(result));await s.waitForTimeout(3000);console.log('[wire teacher post]',JSON.stringify(tw.slice(-20)));console.log('[wire student post]',JSON.stringify(sw.slice(-20)));expect(await app<number>(s,'LV.curSec')).toBe(1);
}finally{if(classId&&lessonId){await app(t,`(async()=>{await sb.from('lesson_assignments').delete().eq('class_id','${classId}').eq('lesson_id','${lessonId}');await sb.from('class_lessons').delete().eq('class_id','${classId}').eq('lesson_id','${lessonId}');await sb.from('lessons').delete().eq('id','${lessonId}').eq('school_id',S.schoolId)})()`).catch(()=>{})}await tc.close();await sc.close()}});
